# -*- coding: utf-8 -*-
"""histogramedr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZsosxXbF_gYz-ZtzCYZw5Y0mMkiZN1KX
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load your dataset
data = pd.read_csv('your_dataset.csv')

# Perform basic EDA
# For example, let's visualize the distribution of a numerical feature
plt.figure(figsize=(10, 6))
sns.histplot(data['numerical_feature'], bins=20, kde=True)
plt.title('Distribution of Numerical Feature')
plt.xlabel('Numerical Feature')
plt.ylabel('Frequency')
plt.show()