# -*- coding: utf-8 -*-
"""linearregression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qJTWqP7c9TxaSkxQF_M9S_h8i6ATTDhY
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

# Generate synthetic data
np.random.seed(0)
X = 2 * np.random.rand(100, 1)
y = 4 + 3 * X + np.random.randn(100, 1)

# Train Linear Regression model
lr_model = LinearRegression()
lr_model.fit(X, y)

# Make predictions
X_new = np.array([[0], [2]])
y_pred = lr_model.predict(X_new)

# Visualize the data and the linear regression line
plt.scatter(X, y)
plt.plot(X_new, y_pred, 'r-')
plt.title('Linear Regression')
plt.xlabel('X')
plt.ylabel('y')
plt.show()