# -*- coding: utf-8 -*-
"""statisticalanalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17hOsSmKemOduTabGHEx64ip0HmSojtuN
"""

import pandas as pd
import numpy as np

# Load exam scores dataset
data = pd.read_csv('exam_scores.csv')

# Calculate descriptive statistics
mean_score = np.mean(data['Score'])
median_score = np.median(data['Score'])
std_dev = np.std(data['Score'])
max_score = np.max(data['Score'])
min_score = np.min(data['Score'])

# Print descriptive statistics
print("Mean Score:", mean_score)
print("Median Score:", median_score)
print("Standard Deviation:", std_dev)
print("Maximum Score:", max_score)
print("Minimum Score:", min_score)